
import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'abacaxi-premium',
    name: 'Abacaxi Premium',
    price: 3500,
    unit: 'unidade',
    description: 'O nosso Abacaxi Premium é cultivado com cuidado nas terras férteis de Malanje. Conhecido pela sua doçura intensa e polpa suculenta, é a escolha perfeita para sobremesas.',
    image: 'https://images.unsplash.com/photo-1550258987-190a2d41a8ba?auto=format&fit=crop&q=80&w=600',
    category: 'Tropicais',
    origin: 'Malanje, Angola',
    producer: 'Fazenda Wete',
    weight: '1.5 - 2.0 kg',
    rating: 4.8,
    reviews: 124,
    isNew: true
  },
  {
    id: 'morangos-huila',
    name: 'Morangos Huíla',
    price: 2000,
    unit: '500g',
    description: 'Morangos frescos colhidos nas terras altas da Huíla, conhecidos pelo seu aroma e doçura natural.',
    image: 'https://images.unsplash.com/photo-1518133910546-b6c2fb7d79e3?auto=format&fit=crop&q=80&w=600',
    category: 'Frutos Vermelhos',
    origin: 'Huíla, Angola',
    producer: 'Família Manuel',
    weight: '500g',
    rating: 4.9,
    reviews: 86
  },
  {
    id: 'laranja-doce',
    name: 'Laranja Doce',
    price: 1200,
    unit: '1kg',
    description: 'Laranjas suculentas ideais para sumos frescos e vitamina C diária.',
    image: 'https://images.unsplash.com/photo-1547514701-42782101795e?auto=format&fit=crop&q=80&w=600',
    category: 'Cítricas',
    origin: 'Kwanza Sul, Angola',
    producer: 'Cooperativa do Kwanza',
    weight: '1kg',
    rating: 4.7,
    reviews: 52
  },
  {
    id: 'manga-especial',
    name: 'Manga Especial',
    price: 2500,
    unit: '1kg',
    description: 'Mangas selecionadas, doces e sem fios, colhidas no ponto perfeito de maturação.',
    image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&q=80&w=600',
    category: 'Tropicais',
    origin: 'Bengo, Angola',
    producer: 'Cooperativa do Bengo',
    weight: '1kg',
    rating: 4.9,
    reviews: 210,
    isNew: true
  },
  {
    id: 'banana-pao',
    name: 'Banana Pão',
    price: 1500,
    unit: 'palma',
    description: 'A autêntica banana pão de Angola, essencial para os pratos típicos e pequenos-almoços saudáveis.',
    image: 'https://images.unsplash.com/photo-1571771894821-ad9902d83f4a?auto=format&fit=crop&q=80&w=600',
    category: 'Tropicais',
    origin: 'Zaire, Angola',
    producer: 'Fazenda Zaire',
    weight: '1.2kg',
    rating: 4.8,
    reviews: 95
  },
  {
    id: 'limao-taiti',
    name: 'Limão Taiti',
    price: 800,
    unit: '500g',
    description: 'Limões sumarentos e frescos para temperos e sumos refrescantes.',
    image: 'https://images.unsplash.com/photo-1590502593747-42a996133562?auto=format&fit=crop&q=80&w=600',
    category: 'Cítricas',
    origin: 'Kwanza Sul, Angola',
    producer: 'Cooperativa do Kwanza',
    weight: '500g',
    rating: 4.6,
    reviews: 40
  },
  {
    id: 'mamao-ouro',
    name: 'Mamão Ouro',
    price: 1800,
    unit: 'unidade',
    description: 'Mamão com polpa firme e doce, extremamente rico em fibras e vitaminas.',
    image: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&q=80&w=600',
    category: 'Tropicais',
    origin: 'Cuanza Norte, Angola',
    producer: 'Fazenda Norte',
    weight: '1.5kg',
    rating: 4.7,
    reviews: 67,
    isNew: true
  }
];
